FROM registry.access.redhat.com/ubi9/python-312:latest as base

FROM base as builder

COPY pyproject.toml .
RUN pip install --no-cache-dir ".[llm-judge]"

FROM builder

WORKDIR /app
ARG CACHEBUST=1
RUN echo "$CACHEBUST"
COPY ./common /app/detectors/common
COPY ./llm_judge/app.py /app/detectors/llm_judge/app.py
COPY ./llm_judge/detector.py /app/detectors/llm_judge/detector.py
RUN touch /app/detectors/llm_judge/__init__.py

EXPOSE 8000
CMD ["uvicorn", "detectors.llm_judge.app:app", "--workers", "4", "--host", "0.0.0.0", "--port", "8000", "--log-config", "/app/detectors/common/log_conf.yaml"]
