FROM registry.access.redhat.com/ubi9/ubi-minimal as base
RUN microdnf update -y && \
    microdnf install -y --nodocs \
        python-pip python-devel && \
    pip install --upgrade --no-cache-dir pip wheel && \
    microdnf clean all

FROM base as builder

COPY ./common/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./llm_judge/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM builder

WORKDIR /app
ARG CACHEBUST=1
RUN echo "$CACHEBUST"
COPY ./common /app/detectors/common
COPY ./llm_judge/app.py /app/detectors/llm_judge/app.py
COPY ./llm_judge/detector.py /app/detectors/llm_judge/detector.py
COPY ./llm_judge/scheme.py /app/detectors/llm_judge/scheme.py
RUN touch /app/detectors/llm_judge/__init__.py

EXPOSE 8000
CMD ["uvicorn", "detectors.llm_judge.app:app", "--workers", "4", "--host", "0.0.0.0", "--port", "8000", "--log-config", "/app/detectors/common/log_conf.yaml"]

# gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000