name: Release Build

# Workflow builds and pushes release detector images to Quay.io
# Image naming convention:
#   ${REGISTRY}/${ORG_PREFIX}/${IMAGE_PREFIX}/${TAG_PREFIX}:${TAG}
# Example: quay.io/rh-ee-mmisiura/guardrails-detectors/hf-detector:1.0.0

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - 'gh_workflows'
env:
  REGISTRY: quay.io
  ORG_PREFIX: rh-ee-mmisiura
  IMAGE_PREFIX: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        detector:
          - name: huggingface
            dockerfile: Dockerfile.hf
            context: detectors
            tag_prefix: hf-detector

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        run: |
          # Get version from tag
          if [[ $GITHUB_REF != refs/tags/* ]]; then
            echo "Error: This workflow only runs on tags"
            exit 1
          fi
          
          IMAGE_BASE="${REGISTRY}/${ORG_PREFIX}/${IMAGE_PREFIX}/${{ matrix.detector.tag_prefix }}"
          IMAGE_TAG="${IMAGE_BASE}:${VERSION}"
          
          echo "Building ${IMAGE_TAG}"
          podman build \
            --platform linux/amd64 \
            -f ${{ matrix.detector.context }}/${{ matrix.detector.dockerfile }} \
            -t ${IMAGE_TAG} \
            ${{ matrix.detector.context }}
          
          echo "Pushing tag"
          podman push ${IMAGE_TAG}