name: Run Tox Tests

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev, gh_workflows ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
          
      - name: Run tox
        run: tox

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: .tox/test-results/